[products]
#格式為 Label ID: [品名, 單價(每重量單位或每個), 計價單位]
#計價單位 --> twkg:台斤, kg:公斤, gram:公克, one:一個
labels_tw = {"v1":["杏仁", 1, "gram"], "v2":["巴西果", 10, "gram"], "v3":["腰果", 1.1, "gram"], "v4":["夏威夷果", 5, "gram"], "v5":["花生", 12, "gram"], "v6":["胡桃", 1, "gram"], "v7":["開心果", 1, "gram"], "v8":["南瓜籽", 2, "gram"], "v9":["杏仁片", 0.9, "gram"],"v10":["核桃", 1, "gram"] }

[camera]
cam_id = 0
#(H, V) 是否水平或垂直翻轉畫面
flipFrame = (False,False)
#是否將過程錄製成影片
record_video = False
#影片檔名
video_out = output.avi
#每秒幀數
frame_rate = 2

[desktop]
#背景圖片的路徑檔名
bg = images/bg.jpg
click_bg = images/bgClick.jpg
#(y,x) 購物車的顯示尺寸
cart_list_size = (350,250)
#僅僅顯示用, 偵測種類
detection_txt = nuts

[operation]
#TW, EN
lang = tw
#seconds 商品結帳的結果, 要顯示幾秒
wait_for_next = 3

[yoloModel]
#yolov3-tiny, yolov3 可選擇YOLO-Tiny或YOLOV3版本
modeltype = yolov3-tiny
objnames = model/10nuts.names
weights = model/10nuts.weights
cfg = model/10nuts.cfg

[system]
#是否切換到全螢幕來執行
full_screen = True
name_win = AI_POS